apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dev-flight-service-hpa
  namespace: dev
  labels:
    env: dev
    app: flight-service
    layer: frontend
spec:
  maxReplicas: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-flight-service-deployment
  targetCPUUtilizationPercentage: 80